# Generated by Django 3.2 on 2023-03-28 02:49

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='GREQuestion',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='questions.choice')),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choices', to='questions.choice')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'GRE Question',
                'verbose_name_plural': 'GRE Questions',
            },
        ),
        migrations.CreateModel(
            name='FSLSMQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.choice')),
            ],
            options={
                'verbose_name': 'FSLSM Question',
                'verbose_name_plural': 'FLSM Questions',
                'ordering': ['order'],
            },
        ),
    ]
