# Generated by Django 3.2 on 2023-03-30 14:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('questions', '0002_auto_20230330_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='GREQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Answer', to='questions.choice')),
                ('choices', models.ManyToManyField(blank=True, to='questions.Choice')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'GRE Question',
                'verbose_name_plural': 'GRE Questions',
            },
        ),
        migrations.CreateModel(
            name='FSLSMQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('choices', models.ManyToManyField(blank=True, to='questions.Choice')),
            ],
            options={
                'verbose_name': 'FSLSM Question',
                'verbose_name_plural': 'FLSM Questions',
                'ordering': ['order'],
            },
        ),
    ]
