# Generated by Django 3.2 on 2023-04-08 03:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('questions', '0003_choice_fslsmquestion_grequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('goal_accuracy', models.FloatField()),
                ('total_questions', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='grequestion',
            name='tags',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.grequestion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_subject_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grequestion',
            name='subjects',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='questions.Subject', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
