# Generated by Django 3.2 on 2023-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20230408_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grequestion',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='Difficulty on the scale of 1-5, 5 being the most difficult'),
        ),
    ]
