# Generated by Django 3.2 on 2023-04-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20230410_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grequestion',
            name='choices',
        ),
    ]
