# Generated by Django 3.2 on 2023-04-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_test', '0003_auto_20230410_1714'),
        ('questions', '0008_remove_grequestion_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='question',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tag',
        ),
        migrations.DeleteModel(
            name='GREQuestion',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
