# Generated by Django 3.2 on 2023-04-10 17:15

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('questions', '0009_auto_20230410_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='GREQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.IntegerField(default=1, help_text='Difficulty on the scale of 1-5, 5 being the most difficult')),
            ],
            options={
                'verbose_name': 'GRE Question',
                'verbose_name_plural': 'GRE Questions',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.grequestion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_subject_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grequestion',
            name='subjects',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='questions.Subject', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
