# Generated by Django 3.2 on 2023-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20230410_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grequestion',
            name='subjects',
        ),
        migrations.AddField(
            model_name='grequestion',
            name='choices',
            field=models.ManyToManyField(blank=True, to='questions.Choice'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
