# Generated by Django 3.2 on 2023-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20230413_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('choices', models.ManyToManyField(blank=True, to='questions.FSLSMChoice')),
            ],
            options={
                'verbose_name': 'Motivation Question',
                'verbose_name_plural': 'Motivation Questions',
                'ordering': ['order'],
            },
        ),
    ]
