# Generated by Django 3.2 on 2023-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_grequestion_choices'),
        ('mock_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='subjects',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questions.GREQuestion'),
        ),
    ]
