# Generated by Django 3.2 on 2023-04-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20230408_1701'),
        ('mock_test', '0002_remove_mocktest_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questions.GREQuestion'),
        ),
    ]
