# Generated by Django 3.2 on 2023-04-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_test', '0002_auto_20230410_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questioninteraction',
            name='question',
        ),
    ]
