# Generated by Django 3.2 on 2023-03-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230327_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
