# Generated by Django 3.2 on 2023-03-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0013_delete_socialauth'),
        ('users', '0003_delete_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('usersocialauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social_django.usersocialauth')),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Social Auth',
                'verbose_name_plural': 'Social Auths',
            },
            bases=('social_django.usersocialauth',),
        ),
    ]
