# Generated by Django 3.2 on 2023-03-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
