# Generated by Django 3.2 on 2023-03-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
