# Generated by Django 3.2 on 2023-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='ls',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
