# Generated by Django 3.2 on 2023-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230408_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_first_test',
            field=models.BooleanField(default=True),
        ),
    ]
