# Generated by Django 3.2 on 2023-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_appuser_motivation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='motivation',
        ),
        migrations.AddField(
            model_name='appuser',
            name='motivation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
