# Generated by Django 3.2 on 2023-04-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230413_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='motivation',
        ),
    ]
