# Generated by Django 3.2 on 2023-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_appuser_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='motivation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
