# Generated by Django 3.2 on 2023-04-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_appuser_motivation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='motivation',
        ),
    ]
